# Generated by Django 6.0.5 on 2026-06-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='plataform',
            new_name='platform',
        ),
    ]
